### ISSUE TITLE
is this plugin still working?

### ISSUE THREAD

**Issue by marcandre83** [dragouf/homebridge-awox#6]
Hi,

I wonder if this plugin is still working? I am getting this error:

 ====================
[2020-4-22 17:31:16] ERROR LOADING PLUGIN homebridge-awox:
[2020-4-22 17:31:16] Error: Cannot find module 'bluetooth-hci-socket'
Require stack:
- /usr/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/hci-socket/hci.js
- /usr/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/hci-socket/bindings.js
- /usr/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/resolve-bindings.js
- /usr/lib/node_modules/homebridge-awox/node_modules/noble-extended/index.js
- /usr/lib/node_modules/homebridge-awox/node_modules/awox-smartlight/src/lib.js
- /usr/lib/node_modules/homebridge-awox/index.js
- /usr/lib/node_modules/homebridge/lib/plugin.js
- /usr/lib/node_modules/homebridge/lib/server.js
- /usr/lib/node_modules/homebridge/lib/cli.js
- /usr/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:980:15)
    at Function.Module._load (internal/modules/cjs/loader.js:862:27)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1156:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1176:10)
    at Module.load (internal/modules/cjs/loader.js:1000:32)
    at Function.Module._load (internal/modules/cjs/loader.js:899:14)
    at Module.require (internal/modules/cjs/loader.js:1042:19)
[2020-4-22 17:31:16] ====================

but I am having a very hard time installing bluetooth-hci-socket on my raspberry pi 4.

**Comment by MichaelMichaelMichaelMichaelMichael** [comment]
Same error here, I've been using the official [Homebridge Raspberry Image](https://github.com/homebridge/homebridge-raspbian-image) with node 12.x shipped. I'd be happy in helping testing in order to get this issue fixed. 

```
[5/17/2020, 14:39:38] ====================
[5/17/2020, 14:39:38] ERROR LOADING PLUGIN homebridge-awox:
[5/17/2020, 14:39:38] Error: Cannot find module 'bluetooth-hci-socket'
Require stack:
- /usr/local/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/hci-socket/hci.js
- /usr/local/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/hci-socket/bindings.js
- /usr/local/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/resolve-bindings.js
- /usr/local/lib/node_modules/homebridge-awox/node_modules/noble-extended/index.js
- /usr/local/lib/node_modules/homebridge-awox/node_modules/awox-smartlight/src/lib.js
- /usr/local/lib/node_modules/homebridge-awox/index.js
- /usr/local/lib/node_modules/homebridge/lib/plugin.js
- /usr/local/lib/node_modules/homebridge/lib/pluginManager.js
- /usr/local/lib/node_modules/homebridge/lib/api.js
- /usr/local/lib/node_modules/homebridge/lib/server.js
- /usr/local/lib/node_modules/homebridge/lib/cli.js
- /usr/local/lib/node_modules/homebridge/bin/homebridge
    at Function.Module._resolveFilename (internal/modules/cjs/loader.js:957:15)
    at Function.Module._load (internal/modules/cjs/loader.js:840:27)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
    at require (internal/modules/cjs/helpers.js:77:18)
    at Object.<anonymous> (/usr/local/lib/node_modules/homebridge-awox/node_modules/noble-extended/lib/hci-socket/hci.js:6:26)
    at Module._compile (internal/modules/cjs/loader.js:1133:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:1153:10)
    at Module.load (internal/modules/cjs/loader.js:977:32)
    at Function.Module._load (internal/modules/cjs/loader.js:877:14)
    at Module.require (internal/modules/cjs/loader.js:1019:19)
[5/17/2020, 14:39:38] ====================
```

**Comment by vdebrist** [comment]
@marcandre83 @MichaelMichaelMichaelMichaelMichael 

First of all you need to install noble, awox-light and after that - homebridge-awox, but it does not matter, plugin not works. 

@dragouf Will you resume your work with this plugin? I have near 30 Awox bulbs and it will be super, if I'll be able to add them into HomeKit.

**Comment by CorbacFR** [comment]
hi @vdebrist can you help me with that please ? my twitter for more simple discussion @Flemmeoriginel . thanks
